-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#131318',
  base01 = '#0e0e13',
  base02 = '#1b1b21',
  base03 = '#46464f',
  base04 = '#c7c5d0',
  base05 = '#e4e1e9',
  base06 = '#303036',
  base07 = '#39383f',

  base08 = '#ffb4ab',
  base09 = '#e8b9d4',
  base0A = '#c5c4dd',
  base0B = '#bfc2ff',
  base0C = '#ffd8ed',
  base0D = '#e0e0ff',
  base0E = '#444559',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#3e4278',
  fg = '#131318',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffd8ed',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e8b9d4',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c5c4dd',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#565992',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0e0e13',
  fg = '#bfc2ff',
})
