-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1a1110',
  base01 = '#140c0b',
  base02 = '#231918',
  base03 = '#534341',
  base04 = '#d8c2bf',
  base05 = '#f1dedc',
  base06 = '#392e2d',
  base07 = '#423735',

  base08 = '#ffb4ab',
  base09 = '#e1c38c',
  base0A = '#e7bdb8',
  base0B = '#ffb3ac',
  base0C = '#fedea6',
  base0D = '#ffdad6',
  base0E = '#5d3f3c',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#73332f',
  fg = '#1a1110',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#fedea6',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e1c38c',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e7bdb8',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#904a44',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#140c0b',
  fg = '#ffb3ac',
})
