# font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        11

# window
window_padding_width 10
hide_window_decorations yes
show_window_resize_notification no
confirm_os_window_close 0
placement_strategy top-left

# keybindings
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# allow remote access
single_instance yes
allow_remote_control yes

# aesthetics
cursor_shape block
cursor_blink_interval 0
enable_audio_bell no

foreground #e4e1e9
background #000000
selection_background #c9c9c9

cursor #e4e1e9
cursor_text_color #c8c5d0

active_border_color #c6c4dd
active_tab_background #c6c4dd
inactive_tab_background   #1c1c1c
inactive_tab_foreground   #b0afac
tab_bar_background        none
tab_bar_margin_color      none

color0                    #000000
color1                    #ed333b
color2                    #57e389
color3                    #ff7800
color4                    #62a0ea
color5                    #9141ac
color6                    #5bc8af
color7                    #deddda

color8                    #9a9996
color9                    #f66151
color10                   #8ff0a4
color11                   #ffa348
color12                   #99c1f1
color13                   #dc8add
color14                   #93ddc2
color15                   #f6f5f4

# minimal tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
