# configs
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/looknfeel.conf
source = ~/.config/hypr/configs/tiling.conf
source = ~/.config/hypr/configs/window-rules.conf

# monitors
env = GDK_SCALE, 1
monitor = DP-2, 2560x1440@165, 1080x310, 1
monitor = HDMI-A-1, disable
