# configs
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/envs.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/looknfeel.conf
source = ~/.config/hypr/configs/tiling.conf
source = ~/.config/hypr/configs/window-rules.conf

# hyprpicker noto-fonts noto-fonts-emoji nwg-look steam thunderbird spotify telegram amneziavpn obs-studio protontricks qbittorrent mission-center keepassxc firefox localsend prismlauncher qdiskinfo helium-browser oracle-virtualbox samrewritten winetricks mangojuice protonup-qt calculator czkawka goverlay imv libre-office mpv nvtop atop obsidian print-settings rofi waydroid yazi ifuse idevicerepair chezmoi github-cli activate-linux

# ---to-install---
# install Stack Sans Text
# install uosc
# install matugen
# install chezmoi
# install screengrab
# install vicinae
# install qdiskinfo
# install mangohud
# unhashtag Color in /etc/pacman.conf
# ---set-cursor---
# $ yay -S apple_cursor
# $ hyprctl setcursor 'macOS (SVG)' 24
# $ gsettings set org.gnome.desktop.interface cursor-theme macOS
# ---gaming---
# for Counter-Strike Classic Offensive: ProtonUp-Qt and lib32-vulkan-radeon
# for Xbox Controller: install https://github.com/dlundqvist/xone and create 50-xone.rules in /etc/udev/rules.d/ and add `ACTION=="add", SUBSYSTEM=="leds", KERNEL=="gip*", ATTR{brightness}="0"`
# for Heroic Games Launcher: add MANGOHUD = 1 to ENV for every game where it's needed
# DXVK_FRAME_RATE=60 %command% for locked 60
# ---davinci-resolve---
# required opencl-amd
# LD_PRELOAD="/usr/lib/libgio-2.0.so /usr/lib/libgmodule-2.0.so /usr/lib/libglib-2.0.so" /opt/resolve/bin/resolve
# ---other---
# for printer: https://archive.org/download/Windows7-iso, extra/virtualbox-host-modules-arch
# cleaning up the packet manager cache: $ pacman -Scc and remove .cache/yay
# $ xdg-settings set default-web-browser helium.desktop
# $ xdg-mime default spotify.desktop x-scheme-handler/spotify
# $ hyprshade on e-ink
# remove omarchy-snapshot from ./.local/share/omarchy/bin/omarchy-update
# to open directories in Nautilus: $ xdg-mime default org.gnome.Nautilus.desktop inode/directory application/x-gnome-saved-search
# https://github.com/PaulCombal/SamRewritten
# set adwaita dark theme in gtk settings, pacman install extra/xdg-desktop-portal-gnome, extra/xdg-desktop-portal-gtk, extra/xdg-desktop-portal-hyprland, libadwaita
# font list: fc-list :spacing=100 -f "%{family[0]}\n" | sort -u

# monitors
env = GDK_SCALE, 1
monitor = DP-2, 2560x1440@165, 0x0, 1
monitor = HDMI-A-1, disable
