# app binds
bindd = SUPER, E, File manager, exec, nautilus --new-window
bindd = SUPER, B, Browser, exec, helium-browser
bindd = SUPER, Z, Editor, exec, zeditor
bindd = SUPER, RETURN, Terminal, exec, kitty
bindd = SUPER, SPACE, Vicinae, exec, vicinae toggle # pkill rofi || rofi -show drun -theme ~/.config/rofi/style.rasi

# utility binds
bindd = SUPER CONTROL, SPACE, Wallpaper selector, exec, ~/.config/hypr/scripts/wallpaper-select.sh
bindd = SUPER SHIFT, V, Clipboard, exec, xdg-open vicinae://extensions/vicinae/clipboard/history
bindd = , Home, Screenshot, exec, ~/.config/hypr/scripts/screenshot-region.sh
bindd = , page_down, Fullscreen Screenshot, exec, ~/.config/hypr/scripts/screenshot-fullscreen.sh
bindd = ALT, Home, Color Picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER, P, Toggle Window Floating, togglefloating
bindd = SUPER SHIFT, L, Lock Screen, exec, pidof hyprlock || hyprlock & hyprctl switchxkblayout all 0 > /dev/null 2>&1
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send "  $(date +"%A %H:%M  —  %d %B W%V %Y")"

# scripts
bindd = SUPER SHIFT, SPACE, Toggle Waybar, exec, ~/.config/hypr/scripts/toggle-waybar.sh
bindd = SUPER SHIFT, J, Toggle second monitor, exec, ~/.config/hypr/scripts/toggle-monitor.sh
bindd = SUPER CONTROL, Z, Start/Save recording, exec, ~/.config/hypr/scripts/recording-save.sh
bindd = SUPER CONTROL, X, Stop recording, exec, ~/.config/hypr/scripts/recording-stop.sh

# other
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')" # only display the OSD on the currently focused monitor
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, $osdclient --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, $osdclient --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, $osdclient --output-volume mute-toggle
bindeld = ,XF86AudioMicMute, Mute microphone, exec, $osdclient --input-volume mute-toggle
bindeld = ALT, XF86AudioRaiseVolume, Volume up precise, exec, $osdclient --output-volume +1
bindeld = ALT, XF86AudioLowerVolume, Volume down precise, exec, $osdclient --output-volume -1
bindld = , XF86AudioNext, Next track, exec, $osdclient --playerctl next
bindld = , XF86AudioPause, Pause, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, $osdclient --playerctl previous

# copy / paste
bindd = SUPER, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = SUPER, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
