# full opacity when focused (optional)
windowrule {
  name = windowrule-1
  opacity = 1.0 override
  match:focus = 1
}

# fix steam tiling
windowrule {
  name = windowrule-2
  tile = on
  match:title = ^(Steam)$
}

# fix monitor sleep when fullscreen
windowrule {
  name = windowrule-3
  idle_inhibit = fullscreen
  match:class = .*
}

# custom rounding
windowrule {
  name = windowrule-4
  rounding = 10
  match:class = awww-daemon
}

# always disable fullscreen unless toggled
windowrule {
  name = windowrule-5
  fullscreen_state = 0
  tile = on
  suppress_event = maximize
  suppress_event = fullscreen
  match:title = ^()$
}

# tile screenshot editor
windowrule {
  name = windowrule-6
  tile = off
  center = on
  size = 1600 900
  match:class = be.alexandervanhee.gradia
}

# tile preview window
windowrule {
  name = windowrule-7
  tile = off
  center = on
  size = 1600 900
  match:class = org.gnome.NautilusPreviewer
}

# tile vkmark
windowrule {
  name = windowrule-8
  tile = off
  center = on
  match:class = com.github.vkmark.vkmark
}

layerrule {
  name = windowrule-9
  no_anim = on
  match:namespace = selection
}
