# fix steam tiling
windowrule {
  name = windowrule-1
  tile = on
  fullscreen = off
  fullscreen_state = 0
  suppress_event = fullscreen fullscreenoutput
  match:class = ^(steam)$
}

# fix monitor sleep when fullscreen
windowrule {
  name = windowrule-2
  idle_inhibit = fullscreen
  match:class = .*
}

# custom awww rounding
windowrule {
  name = windowrule-3
  rounding = 10
  match:class = awww-daemon
}

# always disable fullscreen unless toggled
windowrule {
  name = windowrule-4
  tile = on
  fullscreen = off
  fullscreen_state = 0
  suppress_event = fullscreen fullscreenoutput
  match:title = ^()$
}

# tile screenshot editor
windowrule {
  name = windowrule-5
  tile = off
  center = on
  size = 1600 900
  match:class = be.alexandervanhee.gradia
}

# tile preview window
windowrule {
  name = windowrule-6
  tile = off
  center = on
  size = 1600 900
  match:class = org.gnome.NautilusPreviewer
}

# disable screenshot window animation
layerrule {
  name = windowrule-7
  no_anim = on
  match:namespace = selection
}
