[Base]
CopyFilenameToClipboard=0
autoSave=false
autoSaveFirst=false
defDir=/home/alvaniss/Screenshots
defFilename=screen
defImgFormat=png
defScreenshotType=FullScreen
delay=0
imageQuality=80
includeCursor=false
insDateTimeInFilename=false
noDecorations=false
templateDateTime=yyyy-MM-dd-hh-mm-ss

[Display]
lastSelection=@Rect(628 207 1399 922)
notificationTimeout=5
showNotification=true
showTrayIcon=true
windowHeight=498
windowWidth=640
zoomAroundMouse=false

[GlobalShortcuts]
ActiveWindow=
AreaSelection=
FullScreen=

[LocalShortcuts]
Close=Esc
CopyScreen=Ctrl+C
NewScreen=Ctrl+N
Options=Ctrl+P
SaveScreen=Ctrl+S

[System]
AllowCopies=true
closeInTray=false
enbaleExternalView=true
fitInside=true
remLastScreen=false
